on:
  workflow_dispatch:

jobs:
  lte-integ-test:
    runs-on: macos-10.15
    steps:
      - name: test
        run: |
          sudo port install timeout
          timeout 2 sleep 20
      - name: test2
        run: time timout sleep 20
